# Deber Numpy

Dentro del grupo asignado (2 o 3 estudiantes) realizar 50  ejercicios del archivo: Numpy - 100 Exercises.pdf

Nombres:

-  
- 
- Yépez Marín

#### 1. Import the numpy package under the name np

In [3]:
import numpy as np

#### 2. Print the numpy version and the configuration 

In [4]:
print(np.__version__)

1.24.3


3. Create a 3x3 matrix with values ranging from 0 to 8

In [5]:
values = np.arange(9).reshape(3, 3)
print(f"Los valores de la matriz son: \n {values}" )

Los valores de la matriz son: 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 4. Create a random vector of size 30 and find the mean value (★☆☆)

In [6]:
X=np.random.random(30)
mean=X.mean()
round_values=round(mean,2)
print(f"Valores agregados a la matriz \n\n{X}");
print(f"\nMedia de la matriz {round_values}")

Valores agregados a la matriz 

[0.86125764 0.92587154 0.83233656 0.21698661 0.70627934 0.39341308
 0.24461878 0.90138591 0.93396775 0.80353651 0.31007334 0.08800358
 0.14850057 0.20654147 0.9899607  0.56115667 0.53757269 0.66616779
 0.38789845 0.0263073  0.87045269 0.70788554 0.95659281 0.67931742
 0.9448471  0.81868828 0.07459835 0.8893502  0.07322787 0.79751838]

Media de la matriz 0.59


#### 5. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [7]:
matrix1=np.random.rand(5,3)
matrix2=np.random.rand(3,2)
result=np.dot(matrix1,matrix2)
print(f"Matriz 1\n {matrix1}")
print(f"Matriz 2\n {matrix2}")
print(f"\nProducto: \n{result}")

Matriz 1
 [[0.6802203  0.88767598 0.67473803]
 [0.86025873 0.69935526 0.75526856]
 [0.54752585 0.95734032 0.01072212]
 [0.79948274 0.71433667 0.46666428]
 [0.90588719 0.30332134 0.29614561]]
Matriz 2
 [[0.16033874 0.2716755 ]
 [0.61639361 0.9684616 ]
 [0.33953126 0.50828707]]

Producto: 
[[0.88531812 1.3874399 ]
 [0.82544819 1.29490317]
 [0.68152856 1.08134661]
 [0.72694772 1.14620693]
 [0.43276484 0.69038941]]


Alejandro Moreira

In [8]:
z=np.zeros(10)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
