# Deber Numpy

Dentro del grupo asignado (2 o 3 estudiantes) realizar 50  ejercicios del archivo: Numpy - 100 Exercises.pdf

Nombres:

-  
- 
- Yépez Marín

#### 1. Import the numpy package under the name np

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration 

In [2]:
print(np.__version__)

1.23.5


3. Create a 3x3 matrix with values ranging from 0 to 8

In [7]:
values = np.arange(9).reshape(3, 3)
print(f"Los valores de la matriz son: \n {values}" )

Los valores de la matriz son: 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 4. Create a random vector of size 30 and find the mean value (★☆☆)

In [38]:
X=np.random.random(30)
mean=X.mean()
round_values=round(mean,2)
print(f"Valores agregados a la matriz \n\n{X}");
print(f"\nMedia de la matriz {round_values}")

Valores agregados a la matriz 

[0.50878651 0.83050957 0.07288941 0.21976997 0.30470886 0.74812294
 0.95263009 0.76874964 0.69580087 0.30561777 0.54046688 0.345019
 0.36364761 0.34338651 0.48021903 0.30753666 0.49268005 0.60368956
 0.17955302 0.01450751 0.80287778 0.33978486 0.31687286 0.35033181
 0.58161786 0.2897356  0.10302553 0.70727002 0.9485826  0.01827689]

Media de la matriz 0.45


#### 5. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [43]:
matrix1=np.random.rand(5,3)
matrix2=np.random.rand(3,2)
result=np.dot(matrix1,matrix2)
print(f"Matriz 1\n {matrix1}")
print(f"Matriz 2\n {matrix2}")
print(f"\nProducto: \n{result}")

Matriz 1
 [[0.33683249 0.2962795  0.92875867]
 [0.52066088 0.65209445 0.68897618]
 [0.88057921 0.33078458 0.06495265]
 [0.50809805 0.72607717 0.7264865 ]
 [0.57200726 0.36718531 0.9070591 ]]
Matriz 2
 [[0.36740643 0.44667924]
 [0.95188967 0.93871651]
 [0.70038211 0.14449818]]

Producto: 
[[1.05626578 0.56278248]
 [1.29456272 0.94425604]
 [0.68389257 0.71323494]
 [1.386642   1.01351345]
 [1.19496702 0.73125507]]
