# Deber Numpy

Dentro del grupo asignado (2 o 3 estudiantes) realizar 50  ejercicios del archivo: Numpy - 100 Exercises.pdf

Nombres:

-  
- 
- Yépez Marín

#### 1. Import the numpy package under the name np

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration 

In [3]:
print(np.__version__)

1.23.5


3. Create a 3x3 matrix with values ranging from 0 to 8

In [4]:
values = np.arange(9).reshape(3, 3)
print(f"Los valores de la matriz son: \n {values}" )

Los valores de la matriz son: 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 4. Create a random vector of size 30 and find the mean value (★☆☆)

In [5]:
X=np.random.random(30)
mean=X.mean()
round_values=round(mean,2)
print(f"Valores agregados a la matriz \n\n{X}");
print(f"\nMedia de la matriz {round_values}")

Valores agregados a la matriz 

[0.72520445 0.82374392 0.39319185 0.78253181 0.77238331 0.67103563
 0.57187622 0.14639577 0.19042023 0.47692037 0.38972245 0.93187004
 0.01290271 0.27675761 0.67946075 0.64940146 0.70383564 0.31662025
 0.82164746 0.19376478 0.33633594 0.96872403 0.13730397 0.35662164
 0.42811786 0.34442436 0.40329448 0.12606477 0.58056127 0.63608617]

Media de la matriz 0.49


#### 5. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [6]:
matrix1=np.random.rand(5,3)
matrix2=np.random.rand(3,2)
result=np.dot(matrix1,matrix2)
print(f"Matriz 1\n {matrix1}")
print(f"Matriz 2\n {matrix2}")
print(f"\nProducto: \n{result}")

Matriz 1
 [[0.00782882 0.65115544 0.89023896]
 [0.96255884 0.75233803 0.36762677]
 [0.64863704 0.78269627 0.156674  ]
 [0.23286069 0.34940708 0.6233557 ]
 [0.48196313 0.59574842 0.56276172]]
Matriz 2
 [[0.46516699 0.29171085]
 [0.00479227 0.32691159]
 [0.24872756 0.1870454 ]]

Producto: 
[[0.22818919 0.38166911]
 [0.54279492 0.59549978]
 [0.34444458 0.4743921 ]
 [0.2650393  0.29874903]
 [0.36702268 0.44061293]]


In [7]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
